# Generated by Django 3.2.8 on 2021-10-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
    ]
