# Generated by Django 3.2.8 on 2021-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
