# Generated by Django 3.2.8 on 2021-10-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_order_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='submit',
        ),
    ]
