# Generated by Django 3.2.8 on 2021-10-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_order_submit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='Phone',
            new_name='phone',
        ),
    ]
